version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: robotman_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - robotman_net
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: robotman_redis
    ports:
      - "6379:6379"
    networks:
      - robotman_net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: robotman_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    networks:
      - robotman_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  robotman_net:
    driver: bridge
